version: '1'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - 1433:1433
    volumes:
      - .\docker\sqlserver-data:\var\opt\mssql
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: 1234